name: build-and-publish

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: src
          compiler: xelatex
      - name: Copy
        run: |
          mkdir out
          cp ./src/resume.pdf ./latest.pdf
      - name: Commit latest build
        run: |
          git config --global user.name 'Aaron Aster'
          git config --global user.email 'ajgoodm@users.noreply.github.com'
          git add ./latest.pdf
          git commit -m "latest resume automated build"
          git push origin HEAD:main
