name: pdflatex

on:
  push:
    branches: [ master, ajgoodm/publish-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/resume.tex
      - name: Copy
        run: |
          mkdir out
          cp ./resume.pdf ./out/resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: out/resume.pdf
